grader:
  parallel: True
  load_interval: 10
  nogui: True

classroom:
  course_id: "12345678"

mailer:
  enable_students_mailing: True
  enable_admins_mailing: True
  server: smtp.example.ru
  connection: ssl
  port: 465
  address: mailer@example.com
  password: password
  admins_mail_list:
    - admin1@example.com
    - admin2@example.com
