course_id1:
  course_work_id11:
    filename: filename11
    password: filename11
  course_work_id12:
    filename: filename12
    password: password12
  course_work_id13:
    filename: filename13
    password: password13

course_id2:
  course_work_id21:
    filename: filename21
    password: password21
  course_work_id22:
    filename: filename22
    password: password22
  course_work_id23:
    filename: filename23
    password: password23